### PR TITLE
fix: prevent nullyfing updated record's old relations if no new ones …

### LINKED ISSUE #1: Update action erroneously attempts delete old relations on every request
In case one only wants to update the primary record, the update request nullifies the previous relations even tho there are no new one present in the request body.

### PR DESCRIPTION
**Pull request by nickciolpan**
This request will prevent the undefined follow-up storeRelated calls on update requests with no relationship data

### CODE REVIEW

File: src/reststate-vuex.js [hunk 1]
```diff
@@ -323,7 +323,13 @@ const resourceModule = ({ name: resourceName, httpClient }) => {
           const oldRecord = getters.byId({ id: record.id });
 
           // remove old relationships first
-          if (oldRecord && oldRecord.relationships) {
+          // it only makes sense if we temper with the record's relationships
+          if (
+            oldRecord &&
+            oldRecord.relationships &&
+            record &&
+            record.relationships
```
Comment (DenisaHalmaghi) [inline src/reststate-vuex.js:331]: could you use the optional chaining operator here?
It could make the code a bit more readable since there are 4 conditions to be checked
```suggestion
          if (
            oldRecord?.relationships &&
            record?.relationships
```
